<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/**
 * @var $block \Digitalriver\DrPay\Block\Checkout\Subtotal
 * @see \Magento\Tax\Block\Checkout\Subtotal
 */
?>
<?php
$style = $block->escapeHtmlAttr($block->getStyle());
$colspan = (int) $block->getColspan();
?>
<?php if ($block->displayBoth()) : ?>
<tr class="totals sub excl">
    <th style="<?= /* @noEscape */ $style ?>" class="mark" colspan="<?= /* @noEscape */ $colspan ?>" scope="row">
        <?= $block->escapeHtml(__('Cart Subtotal Excl. Tax')) ?>
    </th>
    <td style="<?= /* @noEscape */ $style ?>" class="amount" data-th="<?= $block->escapeHtmlAttr(__('Cart Subtotal Excl. Tax')) ?>">
        <?= /* @noEscape */ $this->helper(\Magento\Checkout\Helper\Data::class)->formatPrice($block->getTotal()->getValueExclTax()) ?>
    </td>
</tr>
<tr class="totals sub incl">
    <th style="<?= /* @noEscape */ $style ?>" class="mark" colspan="<?= /* @noEscape */ $colspan ?>" scope="row">
        <?= $block->escapeHtml(__('Cart Subtotal Incl. Tax')) ?>
    </th>
    <td style="<?= /* @noEscape */ $style ?>" class="amount" data-th="<?= $block->escapeHtmlAttr(__('Cart Subtotal Incl. Tax')) ?>">
        <?= /* @noEscape */ $this->helper(\Magento\Checkout\Helper\Data::class)->formatPrice($block->getTotal()->getValueInclTax()) ?>
    </td>
</tr>
<?php else : ?>
<tr class="totals sub">
    <th style="<?= /* @noEscape */ $style ?>" class="mark" colspan="<?= /* @noEscape */ $colspan ?>" scope="row">
        <?= $block->escapeHtml(__('Cart Subtotal')) ?>
    </th>
    <td style="<?= /* @noEscape */ $style ?>" class="amount" data-th="<?= $block->escapeHtmlAttr(__('Cart Subtotal')) ?>">
        <?= /* @noEscape */ $this->helper(\Magento\Checkout\Helper\Data::class)->formatPrice($block->getTotal()->getValue()) ?>
    </td>
</tr>
<?php endif; ?>
