<?php
$quoteData = $block->getQuoteData();
?>

<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
                 style="position: absolute;">
        </div>
    </div>
    
    <ul class="opc-progress-bar">
        <li class="opc-progress-bar-item _active">
            <span>Review</span>
        </li>
    </ul>

    <div class="opc-wrapper">
        <ol class="opc" id="checkoutSteps">
            <li id="payment" role="presentation" class="checkout-payment-method" style="display: list-item;">
                <div id="checkout-step-payment" class="step-content" data-role="content" role="tabpanel" aria-hidden="false" style="background: rgb(230, 230, 230);">
                    <form id="co-payment-form" class="form payments" action="<?php echo $block->getUrl($quoteData['placeOrderUrl']); ?>" method="post">
                        <input type="hidden" name="form_key" value="<?php echo (isset($quoteData['formKey']) && !empty($quoteData['formKey'])) ? $quoteData['formKey'] : null; ?>">
                        <fieldset class="fieldset">
                            <div id="checkout-payment-method-load" class="opc-payment" style="">
                                <div class="items payment-methods">
                                    <div class="payment-group" data-repeat-index="0">
                                        <div class="payment-method _active">
                                            <div class="payment-method-content" style="margin-bottom: 50px;">
                                                <div id="payment-data_paypal" class="payment-active" style="display: block;">
                                                    <div class="title"><?php echo (isset($quoteData['paymentMethod']) && !empty($quoteData['paymentMethod'])) ? ucfirst($quoteData['paymentMethod']) : null; ?></div>
                                                </div>
                                                
                                                <div data-role="checkout-messages" class="messages"></div>

                                                <div class="payment-method-billing-address">
                                                    <div class="checkout-billing-address">
                                                        <div class="billing-address-details">
                                                            <label><?php echo (isset($quoteData['billingAddress']['prefix']) && !empty($quoteData['billingAddress']['prefix'])) ? $quoteData['billingAddress']['prefix'] : null ?></label>
                                                            <label><?php echo (isset($quoteData['billingAddress']['firstname']) && !empty($quoteData['billingAddress']['firstname'])) ? $quoteData['billingAddress']['firstname'] : null ?></label>&nbsp;<label><?php echo (isset($quoteData['billingAddress']['middlename']) && !empty($quoteData['billingAddress']['middlename'])) ? $quoteData['billingAddress']['middlename'] : null ?></label>&nbsp;<label><?php echo (isset($quoteData['billingAddress']['lastname']) && !empty($quoteData['billingAddress']['lastname'])) ? $quoteData['billingAddress']['lastname'] : null ?></label>&nbsp;<label><?php echo (isset($quoteData['billingAddress']['suffix']) && !empty($quoteData['billingAddress']['suffix'])) ? $quoteData['billingAddress']['suffix'] : null ?></label><br>
                                                            <label><?php echo (isset($quoteData['billingAddress']['street']) && !empty($quoteData['billingAddress']['street'])) ? $quoteData['billingAddress']['street'] : null ?></label><br>
                                                            <label><?php echo (isset($quoteData['billingAddress']['city']) && !empty($quoteData['billingAddress']['city'])) ? $quoteData['billingAddress']['city'] : null ?></label>&nbsp;<label><?php echo (isset($quoteData['billingAddress']['region']) && !empty($quoteData['billingAddress']['region'])) ? $quoteData['billingAddress']['region'] : null ?></label>&nbsp;<label><?php echo (isset($quoteData['billingAddress']['postcode']) && !empty($quoteData['billingAddress']['postcode'])) ? $quoteData['billingAddress']['postcode'] : null ?></label><br>
                                                            <label><?php echo (isset($quoteData['countryNameBilling']) && !empty($quoteData['countryNameBilling'])) ? $quoteData['countryNameBilling'] : null ?></label><br>
                                                            <label><?php echo (isset($quoteData['billingAddress']['telephone']) && !empty($quoteData['billingAddress']['telephone'])) ? $quoteData['billingAddress']['telephone'] : null ?></label>
                                                        </div>
                                                    </div>
                                                </div>
                                                <input type="hidden" name="sourceId" value="<?php echo $quoteData['sourceId']; ?>">
                                                <div class="actions-toolbar">
                                                    <div class="primary paypal-btn-second" style="display: block; margin-right: 10px;">
                                                        <button class="action primary checkout" type="submit" onclick="jQuery('body').trigger('processStart');" style="line-height: 2.2rem; padding: 14px 17px; font-size: 1.8rem;">
                                                            <span><?php echo __('Place Your Order'); ?></span>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </li>
        </ol>
    </div>
    
    <script>
        window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    
    <aside role="dialog" class="modal-custom opc-sidebar opc-summary-wrapper custom-slide" aria-describedby="modal-content-14" data-role="modal" data-type="custom" tabindex="0" style="margin-top:0;">
        <div data-role="focusable-start" tabindex="0"></div>
        <div class="modal-inner-wrap" data-role="focusable-scope">
            <header class="modal-header">
                <button class="action-close" data-role="closeBtn" type="button"><span>Close</span></button>
            </header>
            <div id="modal-content-14" class="modal-content" data-role="content">
                <div id="opc-sidebar" data-bind="afterRender:setModalElement, mageInit: {
                'Magento_Ui/js/modal/modal':{
                    'type': 'custom',
                    'modalClass': 'opc-sidebar opc-summary-wrapper',
                    'wrapperClass': 'checkout-container',
                    'parentModalClass': '_has-modal-custom',
                    'responsive': true,
                    'responsiveClass': 'custom-slide',
                    'overlayClass': 'modal-custom-overlay',
                    'buttons': []
                }}">

                    <div class="opc-block-summary">
                        <span class="title"><?php echo __('Order Summary'); ?></span>
                        <table class="data table table-totals">
                            <caption class="table-caption"><?php echo __('Order Summary'); ?></caption>
                            <tbody>
                                <tr class="totals sub">
                                    <th class="mark" scope="row"><?php echo __('Cart Subtotal'); ?></th>
                                    <td class="amount">
                                        <span class="price" data-th="Cart Subtotal">
                                        <?php if(isset($quoteData['cartData']['subTotal'])) {
                                            echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($quoteData['cartData']['subTotal'],true,false);
                                        } ?>
                                        </span>
                                    </td>
                                </tr>
                                <tr class="totals shipping excl">
                                    <th class="mark" scope="row">
                                        <span class="label"><?php echo __('Shipping'); ?></span>
                                        <span class="value"><?php echo isset($quoteData['cartData']['shippingDescription'])?$quoteData['cartData']['shippingDescription']:null ?></span>
                                    </th>
                                    <td class="amount">
                                        <span class="price" data-th="Shipping">
                                        <?php if(isset($quoteData['cartData']['shippingAmount'])) {
                                            echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($quoteData['cartData']['shippingAmount'],true,false);
                                        } ?>
                                        </span>
                                    </td>
                                </tr>
                                <tr class="totals-tax">
                                    <th class="mark" scope="row"><?php echo __('Tax'); ?></th>
                                    <td class="amount" data-th="Tax">
                                        <span class="price">
                                        <?php if(isset($quoteData['cartData']['taxAmount'])) {
                                            echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($quoteData['cartData']['taxAmount'],true,false);
                                        } ?>
                                        </span>
                                    </td>
                                </tr>

                                <tr class="grand totals">
                                    <th class="mark" scope="row">
                                        <strong><?php echo __('Order Total'); ?></strong>
                                    </th>
                                    <td class="amount" data-th="Order Total">
                                        <strong><span class="price">
                                            <?php if(isset($quoteData['cartData']['orderTotal'])) {
                                                echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($quoteData['cartData']['orderTotal'],true,false);
                                            } ?>
                                        </span></strong>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        
                        <div class="block items-in-cart">
                            <div class="title" aria-selected="false" aria-expanded="false" tabindex="0" onclick="javascript:toggleContent('.content.minicart-items');">
                                <strong role="heading" aria-level="1">
                                    <span><?php echo isset($quoteData['qtyCount'])?$quoteData['qtyCount']:0 ?></span>
                                    <span><?php echo __(isset($quoteData['itemsCountText'])?$quoteData['itemsCountText']:null); ?></span>
                                </strong>
                            </div>
                            <div class="content minicart-items" data-role="content" role="tabpanel" aria-hidden="true" style="display: none;">
                                <div class="minicart-items-wrapper overflowed">
                                    <ol class="minicart-items">
                                        <?php foreach($quoteData['cartData']['items'] as $item) { ?>
                                        <li class="product-item">
                                            <div class="product">
                                                <span class="product-image-container" style="height: 75px; width: 75px;">
                                                    <span class="product-image-wrapper">
                                                        <img src="<?php echo isset($item['thumbnail']) ? $item['thumbnail'] : null;?> " width="75" height="75" alt="<?php echo isset($item['name']) ? $item['name'] : null; ?>" title="<?php echo isset($item['name']) ? $item['name'] : null; ?>">
                                                    </span>
                                                </span>

                                                <div class="product-item-details">
                                                    <div class="product-item-inner">
                                                        <div class="product-item-name-block">
                                                            <strong class="product-item-name"><?php echo isset($item['name']) ? $item['name'] : null; ?></strong>
                                                            <div class="details-qty">
                                                                <span class="label"><span><?php echo __('Qty'); ?></span></span>
                                                                <span class="value"><?php echo isset($item['quantity']) ? $item['quantity'] : null; ?></span>
                                                            </div>
                                                        </div>
                                                        <div class="subtotal">
                                                            <span class="price-excluding-tax" data-label="Excl. Tax">
                                                                <span class="cart-price">
                                                                    <span class="price">
                                                                    <?php if(isset($item['rowTotal'])) {
                                                                        echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($item['rowTotal'],true,false);
                                                                    } ?>
                                                                    </span>
                                                                </span>
                                                            </span>
                                                        </div>
                                                    </div>

                                                    <?php if(!empty($item['productOptions'])) { ?>
                                                    <div class="product options" onclick="javascript:toggleContent('.content.view-details');">
                                                        <span data-role="title" class="toggle" aria-selected="false" aria-expanded="false" tabindex="0"><span><?php echo __('View Details'); ?></span></span>
                                                        <div data-role="content" class="content view-details" aria-hidden="true" style="display: none;">
                                                            <strong class="subtitle"><span><?php echo __('Options Details'); ?></span></strong>
                                                            <dl class="item-options">
                                                                <?php foreach($item['productOptions'] as $productOption) { ?>
                                                                <dt class="label"><?php echo $productOption['label']; ?></dt>
                                                                <dd class="values"><?php echo $productOption['value']; ?></dd>
                                                                <?php } ?>
                                                            </dl>
                                                        </div>
                                                    </div>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </li>
                                        <?php } ?>
                                    </ol>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php 
                    if(isset($quoteData['isVirtual']) && empty($quoteData['isVirtual'])) { ?>
                    <div class="opc-block-shipping-information">
                        <div class="shipping-information">
                            <div class="ship-to">
                                <div class="shipping-information-title">
                                    <span><?php echo __('Ship To:'); ?></span>
                                </div>
                                <div class="shipping-information-content">                                    
                                    <label><?php echo (isset($quoteData['shippingAddress']['prefix']) && !empty($quoteData['shippingAddress']['prefix'])) ? $quoteData['shippingAddress']['prefix'] : null ?></label>
                                    <label><?php echo (isset($quoteData['shippingAddress']['firstname']) && !empty($quoteData['shippingAddress']['firstname'])) ? $quoteData['shippingAddress']['firstname'] : null ?></label>&nbsp;<label><?php echo (isset($quoteData['shippingAddress']['middlename']) && !empty($quoteData['shippingAddress']['middlename'])) ? $quoteData['shippingAddress']['middlename'] : null ?></label>&nbsp;<label><?php echo (isset($quoteData['shippingAddress']['lastname']) && !empty($quoteData['shippingAddress']['lastname'])) ? $quoteData['shippingAddress']['lastname'] : null ?></label>&nbsp;<label><?php echo (isset($quoteData['shippingAddress']['suffix']) && !empty($quoteData['shippingAddress']['suffix'])) ? $quoteData['shippingAddress']['suffix'] : null ?></label><br>
                                    <label><?php echo (isset($quoteData['shippingAddress']['street']) && !empty($quoteData['shippingAddress']['street'])) ? $quoteData['shippingAddress']['street'] : null ?></label><br>
                                    <label><?php echo (isset($quoteData['shippingAddress']['city']) && !empty($quoteData['shippingAddress']['city'])) ? $quoteData['shippingAddress']['city'] : null ?></label>&nbsp;<label><?php echo (isset($quoteData['shippingAddress']['region']) && !empty($quoteData['shippingAddress']['region'])) ? $quoteData['shippingAddress']['region'] : null ?></label>&nbsp;<label><?php echo (isset($quoteData['shippingAddress']['postcode']) && !empty($quoteData['shippingAddress']['postcode'])) ? $quoteData['shippingAddress']['postcode'] : null ?></label><br>
                                    <label><?php echo (isset($quoteData['countryNameShipping']) && !empty($quoteData['countryNameShipping'])) ? $quoteData['countryNameShipping'] : null ?></label><br>
                                    <label><?php echo (isset($quoteData['shippingAddress']['telephone']) && !empty($quoteData['shippingAddress']['telephone'])) ? $quoteData['shippingAddress']['telephone'] : null ?></label>    
                                </div>
                            </div>
                            <div class="ship-via">
                                <div class="shipping-information-title">
                                    <span><?php echo __('Shipping Method:'); ?></span>
                                </div>
                                <div class="shipping-information-content">
                                    <span class="value"><?php echo isset($quoteData['cartData']['shippingDescription'])?$quoteData['cartData']['shippingDescription']:null ?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div data-role="focusable-end" tabindex="0"></div>
    </aside>
</div>

<script type="text/javascript">
function toggleContent(targetElement) {
    require(["jquery"], function ($) {
        $(targetElement).toggle();
    });
}
</script>
